# Generated by Django 3.2 on 2021-04-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0002_auto_20210417_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leader', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earthseed.book')),
            ],
        ),
    ]
