# Generated by Django 3.2 on 2021-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0005_auto_20210423_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='Butler', upload_to=''),
            preserve_default=False,
        ),
    ]
