# Generated by Django 3.2 on 2021-04-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0006_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='topic_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='reply_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_page',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
