# Generated by Django 3.2 on 2021-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0007_auto_20210427_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='leader',
            new_name='facilitator',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='topic_page',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_page',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='forum_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='reply_page',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_page',
        ),
        migrations.AddField(
            model_name='forum',
            name='topic',
            field=models.ManyToManyField(to='earthseed.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='reply',
            field=models.ManyToManyField(to='earthseed.Reply'),
        ),
    ]
