# Generated by Django 3.2 on 2021-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0008_auto_20210429_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.ManyToManyField(blank=True, to='earthseed.Topic'),
        ),
    ]
