# Generated by Django 3.2 on 2021-04-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0011_auto_20210429_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='topic',
        ),
        migrations.AddField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='earthseed.topic'),
            preserve_default=False,
        ),
    ]
