# Generated by Django 3.2 on 2021-04-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0012_auto_20210429_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='earthseed.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='earthseed.forum'),
        ),
    ]
