# Generated by Django 3.2 on 2021-04-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0015_alter_order_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='earthseed.book'),
        ),
    ]
