# Generated by Django 3.2 on 2021-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthseed', '0016_alter_order_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
